title: Ishii Lab
email: dsksh@jaist.ac.jp
description: >- # this means to ignore newlines until "baseurl:"
  Homepage of Ishii Labratory at JAIST.
  JAIST石井研究室のホームページです．
url: "https://www.dsksh.com"
google_analytics: G-Y2VHM986Y7
github_username:  dsksh
remote_theme: jekyll/minima
plugins:
  - jekyll-remote-theme
  - jekyll-redirect-from
exclude:
  - myscript.sh
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - vendor/
  - vint-201912.zip
  - vint-jcam2020.zip
